# Configuration Options for guard-remote
# minimal configuration:
guard 'remote', hostname: 'example.com', remote: 'test' do
  watch(/.*/)
end

# # complete configuration:
# opts = {
#   :hostname  => 'example.com', # mandatory: remote host 
#   :remote    => 'test',        # mandatory: remote directory
#   :user      => 'username',    # optional: remote user, defaults to current user
#   :sftp_opts => {},            # optional: options passed to Net::SFTP, defaults to {}
#   :debug     => true,          # optional: output debug information, defaults to false
# }

# group 'remote' do
#   guard 'remote', opts do
#     watch(/.*/)
#   end
# end
